import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f5f3ec' },
  screen: { flex: 1 },
  content: { padding: 20, paddingBottom: 32 },
  title: { color: '#17241f', fontSize: 25, fontWeight: '700', marginBottom: 6 },
  body: { color: '#263630', fontSize: 16, lineHeight: 23 },
  muted: { color: '#62716a', fontSize: 14, lineHeight: 21 },
  label: { color: '#263630', fontSize: 14, fontWeight: '600', marginBottom: 6 },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#ccd4ce',
    borderRadius: 8,
    borderWidth: 1,
    color: '#17241f',
    fontSize: 16,
    marginBottom: 14,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  card: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe4de',
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 12,
    padding: 14,
  },
  actionButton: {
    alignItems: 'center',
    backgroundColor: '#1d5d49',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 4,
    minHeight: 46,
    paddingHorizontal: 14,
  },
  actionText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#8d9c93',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  secondaryText: { color: '#244235', fontSize: 14, fontWeight: '600' },
  dangerText: { color: '#9b2924', fontSize: 14, fontWeight: '600' },
  error: { color: '#9b2924', fontSize: 14, lineHeight: 21, marginTop: 8 },
  success: { color: '#1d5d49', fontSize: 14, lineHeight: 21, marginTop: 8 },
  notice: {
    backgroundColor: '#fff4d6',
    borderRadius: 8,
    color: '#624c16',
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 14,
    padding: 12,
  },
  tabs: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe4de',
    borderTopWidth: 1,
    flexDirection: 'row',
    paddingBottom: 8,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  tab: { alignItems: 'center', flex: 1, minHeight: 48, justifyContent: 'center' },
  activeTab: { backgroundColor: '#e5eee8', borderRadius: 8 },
  tabText: { color: '#62716a', fontSize: 12, fontWeight: '600' },
  activeTabText: { color: '#1d5d49' },
});
