from pathlib import Path


EXPECTED_PATHS = [
    "README.md",
    "LICENSE",
    ".gitignore",
    ".env.example",
    "docker-compose.yml",
    "docker-compose.prod.yml",
    "docs/geohazard-project-overview.md",
    "docs/geohazard-development-framework.md",
    "docs/geohazard-system-architecture.md",
    "docs/adr/0001-record-architecture-decisions.md",
    "docs/data-sources.md",
    "docs/runbook.md",
    "docs/api-contracts.md",
    "docs/testing-standards.md",
    "docs/glossary.md",
    "docs/git-workflow.md",
    "docs/error-handling-and-logging.md",
    "docs/superpowers/templates/spec-template.md",
    "docs/superpowers/templates/plan-template.md",
    "docs/superpowers/specs/2026-08-27-geohazard-starter-scaffold-design.md",
    "docs/superpowers/plans/2026-08-27-geohazard-starter-scaffold.md",
    "docs/superpowers/plans/2026-08-29-standards-gap-remediation.md",
    "BACKEND_STANDARDS.md",
    "backend/pyproject.toml",
    "backend/alembic.ini",
    "backend/Dockerfile",
    "backend/app/main.py",
    "backend/app/config.py",
    "backend/app/core/db.py",
    "backend/app/core/redis.py",
    "backend/app/core/logging.py",
    "backend/app/core/security.py",
    "backend/app/models/hazard_event.py",
    "backend/app/models/fault_line.py",
    "backend/app/models/volcano.py",
    "backend/app/models/landslide_zone.py",
    "backend/app/models/user_subscription.py",
    "backend/app/schemas/hazard_event.py",
    "backend/app/schemas/fault_line.py",
    "backend/app/schemas/volcano.py",
    "backend/app/schemas/alert.py",
    "backend/app/api/deps.py",
    "backend/app/api/v1/events.py",
    "backend/app/api/v1/hazards.py",
    "backend/app/api/v1/faults.py",
    "backend/app/api/v1/volcanoes.py",
    "backend/app/api/v1/alerts.py",
    "backend/app/api/v1/subscribe.py",
    "backend/app/services/dedup.py",
    "backend/app/services/proximity.py",
    "backend/app/services/notifications.py",
    "backend/ingestion/scheduler.py",
    "backend/ingestion/celery_app.py",
    "backend/ingestion/sources/usgs.py",
    "backend/ingestion/sources/phivolcs_earthquake.py",
    "backend/ingestion/sources/phivolcs_volcano.py",
    "backend/ingestion/sources/gvp.py",
    "backend/ingestion/sources/gem_faults.py",
    "backend/ingestion/sources/phivolcs_fault_atlas.py",
    "backend/ingestion/sources/landslide_susceptibility.py",
    "backend/ingestion/sources/insar_sentinel1.py",
    "backend/ingestion/scraping/parsers.py",
    "backend/ingestion/validation.py",
    "backend/db/migrations/versions/.gitkeep",
    "backend/db/init_postgis.sql",
    "backend/db/seed/sample_earthquakes.json",
    "backend/db/seed/sample_fault_lines.geojson",
    "backend/tests/unit/test_dedup.py",
    "backend/tests/unit/test_usgs_parser.py",
    "backend/tests/unit/test_phivolcs_parser.py",
    "backend/tests/integration/test_events_api.py",
    "backend/tests/integration/test_proximity_query.py",
    "backend/tests/fixtures/usgs_response_sample.json",
    "backend/tests/fixtures/phivolcs_bulletin_sample.html",
    "backend/tests/conftest.py",
    "web/package.json",
    "web/vite.config.ts",
    "web/tailwind.config.ts",
    "web/tsconfig.json",
    "web/index.html",
    "web/Dockerfile",
    "web/src/main.tsx",
    "web/src/App.tsx",
    "web/src/components/map/MapView.tsx",
    "web/src/components/map/EventMarker.tsx",
    "web/src/components/common/Skeleton.tsx",
    "web/src/components/common/ComingSoon.tsx",
    "web/src/components/common/RiskMeter.tsx",
    "web/src/components/common/SectionHeader.tsx",
    "web/src/components/dashboard/DashboardSidebar.tsx",
    "web/src/pages/Dashboard.tsx",
    "web/src/pages/HistoricalBrowser.tsx",
    "web/src/pages/About.tsx",
    "web/src/pages/DataSources.tsx",
    "web/src/hooks/useEvents.ts",
    "web/src/hooks/useFaultLines.ts",
    "web/src/hooks/useRealtimeAlerts.ts",
    "web/src/hooks/useRevealOnScroll.ts",
    "web/src/api/client.ts",
    "web/src/types/hazard.ts",
    "web/src/types/views.ts",
    "web/src/styles/tokens.css",
    "web/src/styles/base.css",
    "web/src/styles/utilities.css",
    "web/tests/MapView.test.tsx",
    "mobile/package.json",
    "mobile/app.json",
    "mobile/metro.config.js",
    "mobile/ios/.gitkeep",
    "mobile/android/.gitkeep",
    "mobile/src/App.tsx",
    "mobile/src/navigation/RootNavigator.tsx",
    "mobile/src/screens/HomeScreen.tsx",
    "mobile/src/screens/NearbyHazardsScreen.tsx",
    "mobile/src/screens/AlertsScreen.tsx",
    "mobile/src/screens/SavedLocationsScreen.tsx",
    "mobile/src/services/pushNotifications.ts",
    "mobile/src/services/offlineCache.ts",
    "mobile/src/services/api.ts",
    "mobile/src/types/hazard.ts",
    "mobile/tests/offlineCache.test.ts",
    ".github/workflows/backend-ci.yml",
    ".github/workflows/web-ci.yml",
    ".github/workflows/mobile-ci.yml",
    ".github/workflows/deploy-staging.yml",
    "infra/terraform/.gitkeep",
    "infra/nginx/reverse-proxy.conf",
    "data/fault_lines/.gitkeep",
    "data/fault_lines/phivolcs_fault_atlas/.gitkeep",
    "data/volcano_hazard_zones/.gitkeep",
    "data/landslide_susceptibility/.gitkeep",
    "scripts/import_fault_lines.py",
    "scripts/import_landslide_layer.py",
    "scripts/seed_local_db.sh",
    "ml/pyproject.toml",
    "ml/src/ml/train.py",
    "ml/src/ml/ingest_kaggle.py",
    "backend/app/api/v1/risk_profile.py",
    "web/src/pages/RiskProfileExplorer.tsx",
    "scripts/train_risk_profile_models.ps1",
]


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    missing = [path for path in EXPECTED_PATHS if not (root / path).exists()]
    if missing:
        print("Missing expected scaffold paths:")
        for path in missing:
            print(f"- {path}")
        return 1

    print(f"All {len(EXPECTED_PATHS)} expected scaffold paths exist.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
